spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      platform: "postgres"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "Password12!"
    
extra-source:
  url: "http://localhost:8081"

email:
  username: ""
  password: ""
  smtp-host: "smtp.gmail.com"
  port: "587"

logging:
  level:
    root: info
    com.zenyatta: info
